### ISSUE TITLE
Risistar

### ISSUE THREAD

**Issue by Para0234** [quentin-riffault/risistar#1]
Keske...

Un OGame qui a le même nom que MON ogame... surprenant :)

**Comment by quentin-riffault** [comment]
Normal, je t'avais proposé de remplacer le framework que tu utilisais pour le jeu sous php avec un autre (celui-ci donc) sous Nodejs. Par manque de temps, j'ai dû abandonner.

J'ai toujours les logs discord si tu en as besoin, et si tu ne te rappelles plus de moi, je suis Nyzark#5061 sur ce réseau.

N'hésite pas à me contacter si besoin, et si tu le souhaites vraiment je peux toujours modifier le nom ou supprimer le répertoire comme il est obsolète.

**Comment by Para0234** [comment]
Ah oui, je m'en souviens, désolé.
